services:
  
  api:
    depends_on:
      db:
        condition: service_healthy
        restart: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - path: local.env

  db:
    image: postgres:16-alpine
    env_file:
      - path: local.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
