services:
  
  api:
    depends_on:
      db:
        condition: service_started
        restart: true
      redis:
        condition: service_started
        restart: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@postgres:5432/go_bank?sslmode=disable
      - REDIS_ADDRESS=redis:6379

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=go_bank

  redis:
    image: redis:7-alpine
